substitutions:
  devicename: terra-1
  upper_devicename: Terra-1

esphome:
  name: $devicename
  friendly_name: $upper_devicename

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "L+2X86u8xqV6zYROXmXeCR9j07MABOQoT0fABgYOZsE="

ota:
  password: "c60cec62880aa918c6cc9b34b0619c4f"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Terra-1 Fallback Hotspot"
    password: "q9rp9dxLGQDR"

captive_portal:

dallas:
  - pin: 32

i2c:
    sda: 21
    scl: 22
    scan: true
    id: bus_a
sensor:
 
  - platform: aht10
    i2c_id: bus_a
    address: 0x38
    temperature:
      name: ${upper_devicename} Cage Temperature 1
      id:  Cage_Temperature_1
    humidity:
      name: ${upper_devicename} Cage Humidity 1
    update_interval: 5s
  
  - platform: aht10
    i2c_id: bus_a
    address: 0x39
    temperature:
      name: ${upper_devicename} Cage Temperature 2
    humidity:
      name: ${upper_devicename} Cage Humidity 2
    update_interval: 5s
    
  - platform: dallas
    address: 0x1503213189DBA828
    name: ${upper_devicename} Waterproof Temperature 1

  - platform: dallas
    address: 0xCD0321318AF84228
    name: ${upper_devicename} Waterproof Temperature 2
    
  - platform: ct_clamp
    sensor: adc_sensor
    name: ${upper_devicename} Measured Current
    update_interval: 2s
    filters:
      - calibrate_linear:
          # Measured value of 0 maps to 0A
          - 0 -> 0
          # Known load: 0.02A
          # Value shown in logs: 0.22A
          - 0.02 -> 0.22

  # Example source sensor
  - platform: adc
    pin: 36
    id: adc_sensor
    
switch:
  - platform: gpio
    pin: 23
    name: ${upper_devicename} Relay 1

  - platform: gpio
    pin: 19
    name: ${upper_devicename} Relay 2
    id: Relay2
  - platform: gpio
    pin: 18
    name: ${upper_devicename} Relay 3
    
  - platform: gpio
    pin: 17
    name: ${upper_devicename} Relay 4
    
  - platform: gpio
    pin: 16
    name: ${upper_devicename} Relay 5

  - platform: gpio
    pin: 25
    name: ${upper_devicename} Relay 6

  - platform: gpio
    pin: 13
    name: ${upper_devicename} Relay 7
    
  - platform: gpio
    pin: 15
    name: ${upper_devicename} Relay 8

  - platform: gpio
    pin: 26
    name: ${upper_devicename} Buzzer

binary_sensor:
  - platform: gpio
    name: ${upper_devicename} Door 1
    pin:
      number: 27
      inverted: true
      mode: INPUT_PUllUP
 
  - platform: gpio
    name: ${upper_devicename} Door 2
    pin:
      number: 14
      inverted: true
      mode: INPUT_PUllUP
      
number:
  - platform: template
    name: ${upper_devicename} writeaway
    id: writeaway
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1